#!/usr/bin/env python3
"""Generate every labs/<lab>/compose.yaml from one specification.

The generated files are deliberately explicit (no anchors, no 'extends') so a
teacher can read one lab's file on its own. Edit this script, not the outputs.
"""
import os

IMAGE = "${BITCT_IMAGE:-ghcr.io/davidepatti/bitct-lab:2026.10}"
HERE = os.path.dirname(os.path.abspath(__file__))
LABS_DIR = os.path.join(HERE, "..", "labs")

LABS = {
    "dlab00-setup": dict(title="DLAB 00 — Setup check", nodes=["node-a"]),
    "dlab01-auth": dict(title="DLAB 01 — Signatures and address encodings", nodes=["node-a"]),
    "dlab02-transaction": dict(title="DLAB 02 — Two nodes and a transaction lifecycle", nodes=["node-a", "node-b"], peer=False),
    "dlab03-structures": dict(title="DLAB 03 — Hashes, block header and Merkle root", nodes=["node-a"]),
    "dlab04-consensus": dict(title="DLAB 04 — Competing histories and reorganization", nodes=["node-a", "node-b"], peer=True),
    "dlab05-wallet": dict(title="DLAB 05 — Watch-only coordination and recovery", nodes=["node-a", "node-b"], peer=False,
                          signer="node-b"),
    "dlab06-attest": dict(title="DLAB 06 — Device evidence: freshness, replay, rotation, revocation", nodes=["node-a"],
                          d17=True, setup="d17-fixture /lab/d17 >/dev/null"),
    "dlab07-anchor": dict(title="DLAB 07 — Sensor records and Merkle anchoring", nodes=["node-a"],
                          setup="mkdir -p /lab/records && cp -n /usr/share/bitct/dlab07/* /lab/records/"),
    "dlab08-channel": dict(title="DLAB 08 — Lightning channel lifecycle", nodes=["node-a"], ln=["alice", "bob"]),
    "dlab09-routing": dict(title="DLAB 09 — Routing with hidden liquidity", nodes=["node-a"], ln=["alice", "bob", "carol", "dave"]),
    "dlab11-esp32": dict(title="DLAB 11 — ESP32 sensor readings anchored on Bitcoin", nodes=["node-a"], d17=True,
                         gateway=True, miner=True, internet=True),
}


def node_service(name, peers, signer=False):
    cmd = ["bitcoind"] + [f"-addnode={p}:18444" for p in peers]
    if signer:
        cmd.append("-networkactive=0")
    out = [f"  {name}:",
           f"    image: {IMAGE}",
           f"    hostname: {name}",
           f"    command: [{', '.join(repr(c).replace(chr(39), chr(34)) for c in cmd)}]",
           "    restart: \"no\"",
           "    stop_grace_period: 30s",
           "    networks: [lab]",
           f"    volumes: [\"{name}:/data\"]",
           "    healthcheck:",
           "      test: [\"CMD\", \"bitcoin-cli\", \"-rpcconnect=127.0.0.1\", \"getblockchaininfo\"]",
           "      interval: 3s",
           "      timeout: 5s",
           "      retries: 40"]
    if signer:
        out.insert(3, "    # offline signer: P2P networking disabled, it never talks to other nodes")
    return out


def ln_service(name):
    return [f"  {name}:",
            f"    image: {IMAGE}",
            f"    hostname: {name}",
            "    command: [\"lnd\"]",
            f"    environment: {{LND_ALIAS: {name}, LND_BITCOIND: node-a}}",
            "    restart: \"no\"",
            "    stop_grace_period: 30s",
            "    networks: [lab]",
            f"    volumes: [\"{name}:/data\"]",
            "    depends_on: {node-a: {condition: service_healthy}}",
            "    healthcheck:",
            "      test: [\"CMD\", \"lncli\", \"--network=regtest\", \"--lnddir=/data/lnd\", \"getinfo\"]",
            "      interval: 3s",
            "      timeout: 5s",
            "      retries: 60",
            "      start_period: 10s"]


def env_block(lab, spec, extra=None):
    env = {"LAB_ID": lab, "LAB_TITLE": spec["title"], "DASH_NODES": ",".join(spec["nodes"])}
    if spec.get("ln"):
        env["DASH_LN"] = ",".join(spec["ln"])
    if extra:
        env.update(extra)
    lines = ["    environment:"]
    for k, v in env.items():
        lines.append(f"      {k}: \"{v}\"")
    return lines


def compose(lab, spec):
    nodes, ln = spec["nodes"], spec.get("ln", [])
    out = [f"# {spec['title']}",
           "# Generated by tools/gen_compose.py — start with: docker compose up -d --wait",
           f"name: bitct-{lab.split('-')[0]}",
           "",
           "services:"]
    for i, n in enumerate(nodes):
        peers = [p for p in nodes if p != n and spec.get("peer") and i == 0]
        svc = node_service(n, peers, signer=(spec.get("signer") == n))
        if peers:  # start the peers first so the initial addnode connection succeeds
            svc.append("    depends_on: {" + ", ".join(f"{p}: {{condition: service_healthy}}" for p in peers) + "}")
        out += svc
    for n in ln:
        out += ln_service(n)
    deps = {n: "service_healthy" for n in nodes + ln}
    d17 = spec.get("d17")
    if spec.get("miner"):
        out += ["  miner:", f"    image: {IMAGE}", "    command: [\"miner\"]",
                "    environment: {MINER_NODE: node-a, MINER_INTERVAL: \"${MINER_INTERVAL:-30}\"}",
                "    restart: \"no\"", "    networks: [lab]", "    depends_on: {node-a: {condition: service_healthy}}"]
    if spec.get("gateway"):
        out += ["  broker:", f"    image: {IMAGE}", "    command: [\"broker\"]", "    hostname: broker",
                "    restart: \"no\"", "    networks: [lab]",
                "  gateway:", f"    image: {IMAGE}", "    command: [\"gateway\"]", "    hostname: gateway",
                "    restart: unless-stopped",
                "    environment:",
                "      GROUP: \"${GROUP:?set GROUP in the .env file}\"",
                "      MQTT_HOST: \"${MQTT_HOST:-broker.hivemq.com}\"",
                "      MQTT_PORT: \"${MQTT_PORT:-1883}\"",
                "      BATCH_SECONDS: \"${BATCH_SECONDS:-60}\"",
                "      ANCHOR_NETWORK: regtest",
                "      BTC_RPC_HOST: node-a",
                "    networks: [lab, edge]",
                "    volumes: [\"d17:/data/d17\"]",
                "    depends_on: {node-a: {condition: service_healthy}}",
                "  device-sim:",
                "    # optional virtual meter: docker compose --profile sim up -d",
                f"    image: {IMAGE}", "    command: [\"device-sim\", \"--interval\", \"15\"]", "    profiles: [sim]",
                "    restart: \"no\"",
                "    environment:",
                "      GROUP: \"${GROUP:?set GROUP in the .env file}\"",
                "      MQTT_HOST: \"${MQTT_HOST:-broker.hivemq.com}\"",
                "      MQTT_PORT: \"${MQTT_PORT:-1883}\"",
                "    networks: [lab, edge]",
                "    volumes: [\"d17:/data/d17\"]"]
    # lab shell
    extra = {}
    if spec.get("setup"):
        extra["LAB_SETUP"] = spec["setup"]
    if d17 or spec.get("gateway"):
        extra["D17_DB"] = "/data/d17/collector.sqlite"
    if spec.get("gateway"):
        extra["GROUP"] = "${GROUP:?set GROUP in the .env file}"
        extra["MQTT_HOST"] = "${MQTT_HOST:-broker.hivemq.com}"
    out += ["  lab:", f"    image: {IMAGE}", "    hostname: lab", "    command: [\"shell\"]", "    restart: \"no\"",
            "    healthcheck:", "      test: [\"CMD\", \"test\", \"-f\", \"/tmp/lab-ready\"]", "      interval: 2s", "      retries: 90"]
    out += env_block(lab, spec, extra)
    nets = "[lab, edge]" if spec.get("internet") else "[lab]"
    vols = ["lab-home:/lab"] + [f"{n}:/ln/{n}:ro" for n in ln] + (["d17:/data/d17"] if (d17 or spec.get("gateway")) else [])
    out += [f"    networks: {nets}", "    volumes: [" + ", ".join(f'"{v}"' for v in vols) + "]",
            "    depends_on: {" + ", ".join(f"{k}: {{condition: {v}}}" for k, v in deps.items()) + "}"]
    # dashboard
    out += ["  dashboard:", f"    image: {IMAGE}", "    command: [\"dashboard\"]", "    restart: \"no\""]
    out += env_block(lab, spec, {"D17_DB": "/data/d17/collector.sqlite"} if (d17 or spec.get("gateway")) else None)
    dvols = [f"{n}:/ln/{n}:ro" for n in ln] + (["d17:/data/d17"] if (d17 or spec.get("gateway")) else [])
    out += ["    ports: [\"127.0.0.1:${DASHBOARD_PORT:-8080}:8080\"]", "    networks: [lab, edge]"]
    if dvols:
        out.append("    volumes: [" + ", ".join(f'"{v}"' for v in dvols) + "]")
    out.append("    depends_on: {" + ", ".join(f"{k}: {{condition: {v}}}" for k, v in deps.items()) + "}")
    out += ["", "networks:", "  lab:", "    internal: true   # nodes never reach the Internet", "  edge: {}", "", "volumes:"]
    for v in nodes + ln + ["lab-home"] + (["d17"] if (d17 or spec.get("gateway")) else []):
        out.append(f"  {v}: {{}}")
    return "\n".join(out) + "\n"


NOTEBOOK_LAB = "dlab10-graph"
NOTEBOOK_COMPOSE = """# DLAB 10 — Graph learning with hidden liquidity (JupyterLab, no Bitcoin node needed)
# Generated by tools/gen_compose.py — start with: docker compose up -d --wait, then open http://localhost:8888
name: bitct-dlab10

services:
  notebook:
    image: ${BITCT_ML_IMAGE:-ghcr.io/davidepatti/bitct-lab:2026.10-ml}
    hostname: notebook
    restart: "no"
    environment:
      LAB_ID: "dlab10-graph"
      LAB_TITLE: "DLAB 10 — Graph learning with hidden liquidity"
    command: ["bash", "-c", "cp -n /usr/share/bitct/dlab10/*.ipynb /lab/ 2>/dev/null; exec jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --ServerApp.token= --ServerApp.password= --ServerApp.root_dir=/lab"]
    entrypoint: []
    ports: ["127.0.0.1:${NOTEBOOK_PORT:-8888}:8888"]
    volumes: ["lab-home:/lab"]
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:8888/api"]
      interval: 3s
      retries: 60

volumes:
  lab-home: {}
"""


def main():
    d = os.path.join(LABS_DIR, NOTEBOOK_LAB)
    os.makedirs(d, exist_ok=True)
    with open(os.path.join(d, "compose.yaml"), "w") as f:
        f.write(NOTEBOOK_COMPOSE)
    print("wrote", os.path.relpath(d, os.path.join(HERE, "..")))
    for lab, spec in LABS.items():
        d = os.path.join(LABS_DIR, lab)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "compose.yaml"), "w") as f:
            f.write(compose(lab, spec))
        if spec.get("gateway"):
            with open(os.path.join(d, ".env"), "w") as f:
                f.write("# Change GROUP to your group code (letters, digits, '-'); use the same value in the Wokwi sketch.\n"
                        "GROUP=g00-change-me\n"
                        "# Public MQTT broker reachable by Wokwi's virtual Wi-Fi\n"
                        "MQTT_HOST=broker.hivemq.com\nMQTT_PORT=1883\n"
                        "# Seconds between Merkle batches, and between regtest blocks\nBATCH_SECONDS=60\nMINER_INTERVAL=30\n")
        print("wrote", os.path.relpath(d, os.path.join(HERE, "..")))


if __name__ == "__main__":
    main()
