#!/usr/bin/env python3
"""Assemble the single-file Wokwi sketch (sketch.ino) from config.inc, bip340.* and main.inc."""
import os, re
here = os.path.dirname(os.path.abspath(__file__))
def read(n): return open(os.path.join(here, n)).read()
h = read("bip340.h").replace("#pragma once\n", "")
c = read("bip340.cpp").replace('#include "bip340.h"\n', "")
out = (read("config.inc") + "\n" +
       "// ===== BIP340 Schnorr signing (bip340.h / bip340.cpp) ==========================\n" + h + "\n" + c + "\n" +
       read("main.inc"))
open(os.path.join(here, "sketch.ino"), "w").write("// D17 signed meter for Wokwi (ESP32). Edit only the CONFIGURATION block below.\n// (Maintainers: this file is generated by make_sketch.py from config.inc, bip340.* and main.inc.)\n" + out)
print("wrote sketch.ino", len(out.splitlines()), "lines")
