// D17 signed meter for Wokwi (ESP32). Edit only the CONFIGURATION block below.
// (Maintainers: this file is generated by make_sketch.py from config.inc, bip340.* and main.inc.)
// ---------------------------------------------------------------------------
// CONFIGURATION — edit these lines before pressing ▶ in Wokwi
// ---------------------------------------------------------------------------
// GROUP must match GROUP in the lab's .env file (letters, digits, '-').
#define GROUP "g00-change-me"

// Device secret key (lab only!). In the lab shell run:  d17 keygen
// and paste the 64-character secret here. A real meter would generate its key
// inside a secure element and never reveal it.
#define DEVICE_SECRET_HEX "0000000000000000000000000000000000000000000000000000000000000000"

#define DEVICE_ID "D17"
#define KEY_ID "key-A"
#define ENROLLMENT 1
#define AUDIENCE "factory-a.audit"
#define REPORT_INTERVAL_MS 15000

// Network: Wokwi's virtual Wi-Fi reaches the Internet, not your laptop,
// so the meter publishes to a public MQTT broker and the lab subscribes to it.
#define WIFI_SSID "Wokwi-GUEST"
#define WIFI_PASS ""
#define MQTT_HOST "broker.hivemq.com"
#define MQTT_PORT 1883
// ---------------------------------------------------------------------------

// ===== BIP340 Schnorr signing (bip340.h / bip340.cpp) ==========================
// BIP340 Schnorr signatures on secp256k1 using the mbedTLS bignum/ECP API
// shipped with the ESP32 Arduino core (mbedTLS 3.x). Teaching code: it is
// checked against the official BIP340 test vectors, but it is not hardened
// against side channels and must never protect real funds.
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// RNG used by mbedTLS point blinding. The sketch passes esp_fill_random.
typedef void (*bip340_rng_fn)(void *buf, size_t len);
void bip340_set_rng(bip340_rng_fn fn);

// SHA256(SHA256(tag) || SHA256(tag) || msg)
void bip340_tagged_hash(const char *tag, const uint8_t *msg, size_t len, uint8_t out[32]);

// x-only public key of a 32-byte secret key. Returns 0 on success.
int bip340_pubkey(const uint8_t seckey[32], uint8_t pubkey[32]);

// 64-byte signature of a 32-byte message with 32 bytes of auxiliary randomness.
// Returns 0 on success.
int bip340_sign(const uint8_t seckey[32], const uint8_t msg[32], const uint8_t aux[32], uint8_t sig[64]);

void bip340_hex(const uint8_t *in, size_t len, char *out);  // out needs 2*len+1 bytes
int bip340_unhex(const char *hex, uint8_t *out, size_t len);  // returns 0 on success

#ifdef __cplusplus
}
#endif

// BIP340 signing with mbedTLS — see bip340.h

#include <string.h>

#include "mbedtls/bignum.h"
#include "mbedtls/ecp.h"
#include "mbedtls/sha256.h"

static bip340_rng_fn g_rng = 0;

void bip340_set_rng(bip340_rng_fn fn) { g_rng = fn; }

static int rng_cb(void *ctx, unsigned char *buf, size_t len) {
  (void)ctx;
  if (g_rng) {
    g_rng(buf, len);
  } else {
    for (size_t i = 0; i < len; i++) buf[i] = (unsigned char)(i * 131 + 7);  // host tests only
  }
  return 0;
}

void bip340_tagged_hash(const char *tag, const uint8_t *msg, size_t len, uint8_t out[32]) {
  uint8_t th[32];
  mbedtls_sha256((const unsigned char *)tag, strlen(tag), th, 0);
  mbedtls_sha256_context c;
  mbedtls_sha256_init(&c);
  mbedtls_sha256_starts(&c, 0);
  mbedtls_sha256_update(&c, th, 32);
  mbedtls_sha256_update(&c, th, 32);
  mbedtls_sha256_update(&c, msg, len);
  mbedtls_sha256_finish(&c, out);
  mbedtls_sha256_free(&c);
}

// k*G -> affine x (32 bytes) and y parity (1 = odd)
static int mul_g(mbedtls_ecp_group *grp, const mbedtls_mpi *k, uint8_t x[32], int *odd) {
  mbedtls_ecp_point R;
  mbedtls_ecp_point_init(&R);
  uint8_t buf[65];
  size_t olen = 0;
  int ret = mbedtls_ecp_mul(grp, &R, k, &grp->G, rng_cb, 0);
  if (ret == 0) ret = mbedtls_ecp_point_write_binary(grp, &R, MBEDTLS_ECP_PF_UNCOMPRESSED, &olen, buf, sizeof buf);
  if (ret == 0 && olen == 65) {
    memcpy(x, buf + 1, 32);
    *odd = buf[64] & 1;
  } else if (ret == 0) {
    ret = -1;
  }
  mbedtls_ecp_point_free(&R);
  return ret;
}

int bip340_pubkey(const uint8_t seckey[32], uint8_t pubkey[32]) {
  mbedtls_ecp_group grp;
  mbedtls_mpi d;
  int odd = 0, ret;
  mbedtls_ecp_group_init(&grp);
  mbedtls_mpi_init(&d);
  ret = mbedtls_ecp_group_load(&grp, MBEDTLS_ECP_DP_SECP256K1);
  if (ret == 0) ret = mbedtls_mpi_read_binary(&d, seckey, 32);
  if (ret == 0 && (mbedtls_mpi_cmp_int(&d, 0) <= 0 || mbedtls_mpi_cmp_mpi(&d, &grp.N) >= 0)) ret = -2;
  if (ret == 0) ret = mul_g(&grp, &d, pubkey, &odd);
  mbedtls_mpi_free(&d);
  mbedtls_ecp_group_free(&grp);
  return ret;
}

int bip340_sign(const uint8_t seckey[32], const uint8_t msg[32], const uint8_t aux[32], uint8_t sig[64]) {
  mbedtls_ecp_group grp;
  mbedtls_mpi d, k, e, s;
  uint8_t px[32], rx[32], db[32], t[32], buf[96], h[32];
  int odd = 0, ret;
  mbedtls_ecp_group_init(&grp);
  mbedtls_mpi_init(&d); mbedtls_mpi_init(&k); mbedtls_mpi_init(&e); mbedtls_mpi_init(&s);

  ret = mbedtls_ecp_group_load(&grp, MBEDTLS_ECP_DP_SECP256K1);
  // 1. d0 in [1, n-1]; P = d0*G; d = d0 if P.y even else n - d0
  if (ret == 0) ret = mbedtls_mpi_read_binary(&d, seckey, 32);
  if (ret == 0 && (mbedtls_mpi_cmp_int(&d, 0) <= 0 || mbedtls_mpi_cmp_mpi(&d, &grp.N) >= 0)) ret = -2;
  if (ret == 0) ret = mul_g(&grp, &d, px, &odd);
  if (ret == 0 && odd) {  // d = n - d0 (use a temporary: X and B must not alias)
    ret = mbedtls_mpi_sub_mpi(&s, &grp.N, &d);
    if (ret == 0) ret = mbedtls_mpi_copy(&d, &s);
  }
  // 2. t = bytes(d) XOR hash_aux(a)
  if (ret == 0) ret = mbedtls_mpi_write_binary(&d, db, 32);
  if (ret == 0) {
    bip340_tagged_hash("BIP0340/aux", aux, 32, h);
    for (int i = 0; i < 32; i++) t[i] = db[i] ^ h[i];
    // 3. k0 = int(hash_nonce(t || P.x || m)) mod n
    memcpy(buf, t, 32); memcpy(buf + 32, px, 32); memcpy(buf + 64, msg, 32);
    bip340_tagged_hash("BIP0340/nonce", buf, 96, h);
    ret = mbedtls_mpi_read_binary(&k, h, 32);
  }
  if (ret == 0) ret = mbedtls_mpi_mod_mpi(&k, &k, &grp.N);
  if (ret == 0 && mbedtls_mpi_cmp_int(&k, 0) == 0) ret = -3;
  // 4. R = k0*G; k = k0 if R.y even else n - k0
  if (ret == 0) ret = mul_g(&grp, &k, rx, &odd);
  if (ret == 0 && odd) {  // k = n - k0
    ret = mbedtls_mpi_sub_mpi(&s, &grp.N, &k);
    if (ret == 0) ret = mbedtls_mpi_copy(&k, &s);
  }
  // 5. e = int(hash_challenge(R.x || P.x || m)) mod n
  if (ret == 0) {
    memcpy(buf, rx, 32); memcpy(buf + 32, px, 32); memcpy(buf + 64, msg, 32);
    bip340_tagged_hash("BIP0340/challenge", buf, 96, h);
    ret = mbedtls_mpi_read_binary(&e, h, 32);
  }
  if (ret == 0) ret = mbedtls_mpi_mod_mpi(&e, &e, &grp.N);
  // 6. s = (k + e*d) mod n; sig = R.x || s
  if (ret == 0) ret = mbedtls_mpi_mul_mpi(&s, &e, &d);
  if (ret == 0) ret = mbedtls_mpi_add_mpi(&s, &s, &k);
  if (ret == 0) ret = mbedtls_mpi_mod_mpi(&s, &s, &grp.N);
  if (ret == 0) {
    memcpy(sig, rx, 32);
    ret = mbedtls_mpi_write_binary(&s, sig + 32, 32);
  }
  memset(db, 0, sizeof db); memset(t, 0, sizeof t);
  mbedtls_mpi_free(&d); mbedtls_mpi_free(&k); mbedtls_mpi_free(&e); mbedtls_mpi_free(&s);
  mbedtls_ecp_group_free(&grp);
  return ret;
}

void bip340_hex(const uint8_t *in, size_t len, char *out) {
  static const char *digits = "0123456789abcdef";
  for (size_t i = 0; i < len; i++) {
    out[2 * i] = digits[in[i] >> 4];
    out[2 * i + 1] = digits[in[i] & 15];
  }
  out[2 * len] = 0;
}

static int nib(char c) {
  if (c >= '0' && c <= '9') return c - '0';
  if (c >= 'a' && c <= 'f') return c - 'a' + 10;
  if (c >= 'A' && c <= 'F') return c - 'A' + 10;
  return -1;
}

int bip340_unhex(const char *hex, uint8_t *out, size_t len) {
  if (strlen(hex) != 2 * len) return -1;
  for (size_t i = 0; i < len; i++) {
    int hi = nib(hex[2 * i]), lo = nib(hex[2 * i + 1]);
    if (hi < 0 || lo < 0) return -1;
    out[i] = (uint8_t)(hi << 4 | lo);
  }
  return 0;
}

// ===========================================================================
// D17 — a simulated factory electricity meter that signs every reading.
// Course "Blockchain for Decentralized Security in IoT" — Docker lab DLAB 11.
//
// Every REPORT_INTERVAL_MS the ESP32:
//   1. reads the "current sensor" (the slide potentiometer) and converts it to watts;
//   2. writes the exact D17 report bytes (schema, device, key, enrollment, seq, …);
//   3. signs m = TaggedHash(schema, bytes) with BIP340 Schnorr (secp256k1);
//   4. publishes {"report", "sig", "pub"} over MQTT to bitct/<GROUP>/d17/report.
// The lab's Docker gateway verifies, batches and anchors the readings on Bitcoin.
//
// Buttons: REPLAY re-sends the last message unchanged; TAMPER changes the value
// after signing. Watch how the gateway classifies both.
// ===========================================================================
#include <WiFi.h>
#include <PubSubClient.h>
#include <Wire.h>
#include <LiquidCrystal_I2C.h>
#include <time.h>
#include "esp_random.h"

#define POT_PIN 34
#define LED_PIN 2
#define BTN_REPLAY 4
#define BTN_TAMPER 5
#define MAX_WATTS 3000

LiquidCrystal_I2C lcd(0x27, 16, 2);
WiFiClient net;
PubSubClient mqtt(net);

uint8_t seckey[32], pubkey[32];
char pubhex[65];
char topic[96];
uint64_t seq = 1;
String lastMsg, lastReport;
int lastWatts = 0;
unsigned long lastSend = 0;
int prevReplay = HIGH, prevTamper = HIGH;  // buttons act once per press

static void rng(void *buf, size_t len) { esp_fill_random(buf, len); }

static void lcdLine(int row, const String &s) {
  String t = s;
  while (t.length() < 16) t += ' ';
  lcd.setCursor(0, row);
  lcd.print(t.substring(0, 16));
}

static String jsonEscape(const String &s) {
  String o;
  for (size_t i = 0; i < s.length(); i++) {
    char c = s[i];
    if (c == '\n') o += "\\n";
    else if (c == '"' || c == '\\') { o += '\\'; o += c; }
    else o += c;
  }
  return o;
}

static String buildReport(uint64_t s, int watts) {
  String r = "course.factory-telemetry.v1\n";
  r += "device=" DEVICE_ID "\n";
  r += "key=" KEY_ID "\n";
  r += "enrollment=" + String(ENROLLMENT) + "\n";
  r += "seq=" + String((unsigned long long)s) + "\n";
  r += "quantity=active-power\n";
  r += "value=" + String(watts) + "\n";
  r += "unit=W\n";
  r += "audience=" AUDIENCE;
  return r;
}

static String signReport(const String &report, unsigned long *ms) {
  uint8_t m[32], aux[32], sig[64];
  char sighex[129];
  unsigned long t0 = millis();
  bip340_tagged_hash("course.factory-telemetry.v1", (const uint8_t *)report.c_str(), report.length(), m);
  esp_fill_random(aux, sizeof aux);
  if (bip340_sign(seckey, m, aux, sig) != 0) return "";
  *ms = millis() - t0;
  bip340_hex(sig, 64, sighex);
  return String(sighex);
}

static void connectWiFi() {
  lcdLine(1, "WiFi...");
  WiFi.begin(WIFI_SSID, WIFI_PASS, 6);
  while (WiFi.status() != WL_CONNECTED) delay(100);
  Serial.printf("WiFi connected, IP %s\n", WiFi.localIP().toString().c_str());
}

static void connectMQTT() {
  while (!mqtt.connected()) {
    lcdLine(1, "MQTT...");
    String id = String("d17-") + GROUP + "-" + String((uint32_t)esp_random(), HEX);
    if (mqtt.connect(id.c_str())) {
      Serial.printf("MQTT connected to %s:%d, topic %s\n", MQTT_HOST, MQTT_PORT, topic);
    } else {
      Serial.printf("MQTT connect failed (state %d), retrying\n", mqtt.state());
      delay(2000);
    }
  }
}

static void publish(const String &msg, const char *what) {
  bool ok = mqtt.publish(topic, msg.c_str());
  digitalWrite(LED_PIN, HIGH);
  Serial.printf("published %s (%u bytes): %s\n", what, msg.length(), ok ? "OK" : "FAILED");
  delay(80);
  digitalWrite(LED_PIN, LOW);
}

void setup() {
  Serial.begin(115200);
  pinMode(LED_PIN, OUTPUT);
  pinMode(BTN_REPLAY, INPUT_PULLUP);
  pinMode(BTN_TAMPER, INPUT_PULLUP);
  Wire.begin(21, 22);
  lcd.init();
  lcd.backlight();
  lcdLine(0, "D17 meter boot");

  bip340_set_rng(rng);
  if (bip340_unhex(DEVICE_SECRET_HEX, seckey, 32) != 0 || bip340_pubkey(seckey, pubkey) != 0) {
    Serial.println("ERROR: DEVICE_SECRET_HEX must be 64 hex characters (run 'd17 keygen')");
    lcdLine(1, "bad secret key");
    while (true) delay(1000);
  }
  bip340_hex(pubkey, 32, pubhex);
#ifdef D17_SELFTEST
  {  // maintainers: compare with the Python reference (tests/selftest_esp32.sh)
    String r = buildReport(42, 1200);
    uint8_t m[32], aux[32] = {0}, sig[64];
    char hx[129];
    bip340_tagged_hash("course.factory-telemetry.v1", (const uint8_t *)r.c_str(), r.length(), m);
    unsigned long t0 = millis();
    bip340_sign(seckey, m, aux, sig);
    bip340_hex(sig, 64, hx);
    Serial.printf("SELFTEST pub %s\nSELFTEST sig %s\nSELFTEST ms %lu\n", pubhex, hx, millis() - t0);
    while (true) delay(1000);
  }
#endif
  snprintf(topic, sizeof topic, "bitct/%s/d17/report", GROUP);

  Serial.println();
  Serial.println("=== D17 signed meter ===");
  Serial.printf("device %s, key %s, enrollment %d\n", DEVICE_ID, KEY_ID, ENROLLMENT);
  Serial.printf("public key (x-only) for enrollment:\n%s\n", pubhex);

  connectWiFi();
  // Wokwi does not keep flash between runs, so the counter starts from the
  // boot time (seconds since 1970). It still increases across restarts.
  configTime(0, 0, "pool.ntp.org", "time.google.com");
  lcdLine(1, "NTP time...");
  time_t now = 0;
  for (int i = 0; i < 100 && now < 1700000000; i++) { delay(100); time(&now); }
  if (now >= 1700000000) {
    seq = (uint64_t)now;
    Serial.printf("first sequence number (boot time): %llu\n", (unsigned long long)seq);
  } else {
    Serial.println("WARNING: no network time; counter restarts at 1 (expect NO_NEW_EVENT)");
  }
  mqtt.setServer(MQTT_HOST, MQTT_PORT);
  mqtt.setBufferSize(1024);
  connectMQTT();
  lastSend = millis() - REPORT_INTERVAL_MS + 2000;
}

void loop() {
  if (WiFi.status() != WL_CONNECTED) connectWiFi();
  if (!mqtt.connected()) connectMQTT();
  mqtt.loop();

  if (millis() - lastSend >= REPORT_INTERVAL_MS) {
    lastSend = millis();
    int raw = analogRead(POT_PIN);
    int watts = (int)((long)raw * MAX_WATTS / 4095);
    String report = buildReport(seq, watts);
    unsigned long ms = 0;
    String sig = signReport(report, &ms);
    if (sig.length() == 128) {
      String msg = String("{\"v\":1,\"report\":\"") + jsonEscape(report) + "\",\"sig\":\"" + sig +
                   "\",\"pub\":\"" + pubhex + "\"}";
      Serial.println("--- report bytes ---");
      Serial.println(report);
      Serial.printf("--- BIP340 signature (%lu ms) ---\n%s\n", ms, sig.c_str());
      publish(msg, "reading");
      lcdLine(0, "D17 " + String(watts) + " W");
      String s = String((unsigned long long)seq);
      lcdLine(1, "seq .." + s.substring(s.length() > 6 ? s.length() - 6 : 0) + " OK");
      lastMsg = msg;
      lastReport = report;
      lastWatts = watts;
      seq++;
    }
  }

  int replay = digitalRead(BTN_REPLAY), tamper = digitalRead(BTN_TAMPER);
  if (replay == LOW && prevReplay == HIGH && lastMsg.length()) {
    publish(lastMsg, "REPLAY of the last message");
    lcdLine(1, "REPLAY sent");
    delay(400);
  }
  if (tamper == LOW && prevTamper == HIGH && lastMsg.length()) {
    String forged = lastMsg;
    forged.replace("value=" + String(lastWatts) + "\\n", "value=" + String(lastWatts + 1000) + "\\n");
    publish(forged, "TAMPERED copy (value +1000 W, old signature)");
    lcdLine(1, "TAMPER sent");
    delay(400);
  }
  prevReplay = replay;
  prevTamper = tamper;
  delay(10);
}
