"""Student-facing text for every Docker lab: meaning, network choice, per-step explanations.

Combined with labsteps.py (the executable commands) to generate README.md, lab-help and decks.
`steps` maps a step id to (student command or None to reuse the test command, why, checkpoint).
"""

COMMON_START = "cd bitct-lab/labs/{lab}\ndocker compose up -d --wait\ndocker compose exec lab bash"

META = {}

META["dlab00-setup"] = dict(
    deck="DLAB 00 — Setting Up the Docker Lab", stable="LAB-SETUP", session="before the first Docker lab (at home)", minutes="30–45",
    lecture="all Docker labs", network="regtest",
    network_why="A private regtest chain starts at block 0 on your laptop, mines blocks on demand and is deleted by a reset.",
    goal="Install Docker, start the course image once, open the lab shell and the dashboard, and practise stop/reset.",
    meaning=["Every Docker lab uses the same course image: Bitcoin Core, LND and the course tools are already inside.",
             "Your laptop only runs Docker; nothing else is installed or changed.",
             "Each lab folder is a small, disposable network of containers that you can reset at any time."],
    steps={"S1": (None, "Ask the node which chain it follows.", "\"chain\": \"regtest\", \"blocks\": 0"),
           "S2": (None, "Create a block on demand: only possible on regtest.", "height now 1"),
           "S3": (None, "One line per node of the running lab.", "node-a chain=regtest height=1"),
           "S4": ("open http://localhost:8080", "The dashboard shows the same chain in your browser.", "block height 1 on the Overview page")},
    submit="Nothing to submit: show the dashboard with height 1 to the teacher at the start of the first lab.",
    limits=["regtest coins have no value and exist only on your computer",
            "the lab RPC password is public on purpose; never reuse it"])

META["dlab01-auth"] = dict(
    deck="DLAB 01 — Signatures and Address Encodings", stable="LAB-BTC-AUTH", session="1", minutes="180", lecture="M 2.0 / M 2.1",
    network="regtest", network_why="Signing and decoding are offline operations; the regtest node only provides wallet RPCs. No public network is needed.",
    goal="Sign exact data, verify it, cause controlled failures, and decode current Bitcoin address encodings.",
    meaning=["A signature binds one key to one exact message: change a byte or the key and verification fails.",
             "An address is an encoding of a locking condition (hash or key) plus a network prefix and a checksum.",
             "Neither a valid signature nor a valid address proves identity, ownership by a person, or truth."],
    steps={"A1": (None, "A BIP340 key pair: 32-byte secret, 32-byte x-only public key.", "secret key and public key in hex"),
           "A2": (None, "Sign the tagged hash of the exact text.", "a 64-byte signature: R.x and s"),
           "A3": (None, "Anyone with the public key can check it.", "VALID"),
           "A4": (None, "One character changes the message hash.", "INVALID"),
           "A5": ("bip340 verify --pubkey $OTHER --text 'D17 reports 1200 W' --sig $SIG", "A different key cannot verify it.", "INVALID"),
           "A6": (None, "Our teaching implementation reproduces the official BIP340 vectors.", "19/19"),
           "B1": ("bitcoin-cli createwallet alice\nLEG=$(bitcoin-cli -rpcwallet=alice getnewaddress '' legacy)\nMSIG=$(bitcoin-cli -rpcwallet=alice signmessage $LEG 'D17 reports 1200 W')\nbitcoin-cli verifymessage $LEG $MSIG 'D17 reports 1200 W'\nbitcoin-cli verifymessage $LEG $MSIG 'D17 reports 1201 W'",
                  "Bitcoin Core's legacy message signing: ECDSA tied to a P2PKH address.", "true, then false"),
           "C1": (None, "One wallet, four address families.", "m/n…, 2…, bcrt1q…, bcrt1p…"),
           "C2": (None, "Decode a Taproot address field by field.", "bech32m, regtest, witness v1, 32-byte key"),
           "C3": ("cat /usr/share/bitct/dlab01/addresses.txt\naddr decode <address>     # for each of A … J", "Real and broken examples: which checks fail?", "G: checksum; H, I: wrong variant; J: mixed case"),
           "C4": (None, "A regtest node rejects a mainnet address.", "isvalid false, then true")},
    submit="Verification matrix (valid / changed text / other key), decoded-address table A–J, and a 3-line claim-boundary note.",
    limits=["a valid signature proves control of a key, not who controls it",
            "a valid address proves correct encoding, not that anyone will ever spend from it"])

META["dlab02-transaction"] = dict(
    deck="DLAB 02 — Two Nodes and a Transaction Lifecycle", stable="LAB-BTC-NETWORK + LAB-BTC-TRANSACTION", session="2", minutes="180",
    lecture="M 2.1", network="regtest",
    network_why="Confirmation must happen when we decide; regtest mines instantly and both nodes are ours. Signet is used in LAB01–LAB07 for the public experience.",
    goal="Connect two nodes, follow a payment from wallet to mempool to block, then build, sign and broadcast PSBTs for P2WPKH and P2TR outputs.",
    meaning=["Nodes relay transactions (mempool) before any miner confirms them.",
             "A PSBT separates building, signing and broadcasting: three roles that can live on different devices.",
             "A failure can come from the signature (consensus) or from node policy (relay fee): different layers."],
    steps={"N1": ("btc-a getblockcount\nbtc-b getblockcount\nbtc-a getconnectioncount", "Two fresh nodes, no peers.", "0 0 0"),
           "N2": ("btc-a addnode node-b:18444 add\nbtc-a getpeerinfo | jq -r '.[].addr'\nbtc-b getconnectioncount", "Make them peers.", "node-b:18444 and 1 connection"),
           "N3": ("btc-a createwallet miner\nbtc-b createwallet receiver\nMINER=$(btc-a -rpcwallet=miner getnewaddress)\nbtc-a generatetoaddress 101 $MINER\nbtc-b getblockcount\nbtc-a -rpcwallet=miner getbalance",
                  "101 blocks: the first reward matures after 100 more.", "both at 101, balance 50"),
           "N4": (None, "A payment travels through the network before it is confirmed.", "the same txid in both mempools"),
           "N5": ("btc-a generatetoaddress 1 $MINER\nbtc-b getblockcount\nbtc-b -rpcwallet=receiver getbalance", "One block confirms it on both nodes.", "102 and 1.00000000"),
           "P1": (None, "A P2WPKH coin for Alice: this is the UTXO she will spend.", "one UTXO of 0.5"),
           "P2": (None, "An unsigned proposal: inputs, outputs (payment + change) and fee.", "fee 0.00000705, no signature yet"),
           "P3": (None, "Sign, finalize, ask the node before broadcasting.", "allowed: true, vsize 141"),
           "P4": (None, "P2WPKH witness = signature + public key.", "two witness items"),
           "P5": (None, "Taproot key-path spend: one 64-byte Schnorr signature, smaller vsize.", "vsize ≈ 130, one witness item"),
           "P6": (None, "Confirm both on node B.", "confirmations=1"),
           "F1": ("# change one output amount after signing, then:\nbtc-a testmempoolaccept '[\"'$TAMPERED'\"]'", "The signature covers the outputs.", "Invalid Schnorr signature (consensus)"),
           "F2": ("btc-a finalizepsbt $P", "An unsigned PSBT is not a transaction yet.", "complete: false"),
           "F3": ("# a PSBT built with fee_rate 0.01 sat/vB\nbtc-a testmempoolaccept '[\"'$RL'\"]'", "Valid, but below the node's relay policy.", "min relay fee not met (policy)")},
    submit="Decoded PSBT summaries (before/after signing), txids, fee and change, the P2WPKH vs P2TR witness comparison, and the classified failures.",
    limits=["regtest fees and timing do not represent mainnet economics",
            "testmempoolaccept reports this node's policy; another node may differ"])

META["dlab03-structures"] = dict(
    deck="DLAB 03 — Hashes, Block Header and Merkle Root", stable="LAB-BTC-STRUCTURES", session="3", minutes="180", lecture="M 2.2",
    network="regtest", network_why="We need a block whose transactions we chose, and the freedom to recompute proof of work: only regtest makes that instant.",
    goal="Hash exact bytes, decode a real 80-byte header, rebuild the Merkle root and see why a change breaks the chain of commitments.",
    meaning=["A hash commits to exact bytes: one byte changes about half the output bits.",
             "The header commits to all transactions through one 32-byte Merkle root.",
             "Changing a transaction forces a new root, a new proof of work and a new hash for every later block."],
    steps={"H1": (None, "Avalanche effect.", "≈128 of 256 bits differ"),
           "H2": ("bitcoin-cli createwallet miner\nmine 101\n# send three payments, then\nmine 1\nbitcoin-cli getblock $(bitcoin-cli getbestblockhash) | jq '{height, nTx, merkleroot}'",
                  "A block with a coinbase and three payments.", "nTx: 4"),
           "H3": ("header block $H", "Six fields, 80 bytes, one double SHA-256.", "proof of work: hash ≤ target → yes"),
           "H4": ("merkle bitcoin $H", "Pairwise double hashing up to the root (odd levels duplicate the last hash).", "MATCH"),
           "H5": ("merkle bitcoin $H --change 2", "One bit in one txid.", "DIFFERENT"),
           "H6": ("FORGED=$(bitcoin-util grind $(header replace-root $OLD $NEWROOT))\nheader decode $FORGED", "Regtest proof of work is trivial: the forged header is 'valid' in isolation.", "a new block hash"),
           "H7": (None, "But the next block still names the original hash.", "previousblockhash ≠ forged hash")},
    submit="Header field table, the Merkle levels for your block, and one paragraph: why does a changed transaction break the chain?",
    limits=["regtest difficulty is minimal: mainnet would need the network's work for every replaced block",
            "Bitcoin's Merkle rules (double SHA-256, duplicated last hash) differ from the receipt trees in DLAB 07/11"])

META["dlab04-consensus"] = dict(
    deck="DLAB 04 — Competing Histories and Reorganization", stable="LAB-BTC-CONSENSUS", session="4", minutes="180", lecture="M 2.3",
    network="regtest", network_why="A reorganization needs two private miners and a network we can cut and restore. Signet's block production is controlled by its signers.",
    goal="Split two nodes, let each extend its own valid history, reconnect them and observe which chain wins and what happens to a transaction.",
    meaning=["Two valid histories can exist at the same time while nodes cannot talk.",
             "Nodes choose the valid chain with the most cumulative work, not the first or the longest by count.",
             "A confirmed transaction can return to the mempool after a reorganization; it does not become invalid."],
    steps={"C1": ("btc-a createwallet miner; btc-b createwallet bob\nmine 101\nbtc-b getblockcount", "One shared history.", "both at 101"),
           "C2": ("BOB=$(btc-b -rpcwallet=bob getnewaddress)\nT=$(btc-a -rpcwallet=miner sendtoaddress $BOB 2)\nbtc-b getrawmempool", "Payment T is known to both nodes.", "T in both mempools"),
           "C3": ("btc-b setnetworkactive false\nbtc-a getconnectioncount", "Cut the network.", "0 connections"),
           "C4": ("mine 1\nbtc-a -rpcwallet=miner gettransaction $T | jq .confirmations", "A confirms T in block 102.", "1 confirmation"),
           "C5": ("btc-b generateblock $BADDR '[]'     # twice", "B mines two blocks without T.", "B at height 103"),
           "C6": ("btc-a getchaintips\nbtc-b getchaintips", "Two different active tips.", "102 on A, 103 on B"),
           "C7": ("btc-b setnetworkactive true\nbtc-a addnode node-b:18444 onetry\nbtc-a getchaintips", "Reconnect: A switches to B's chain.", "103 active, 102 valid-fork"),
           "C8": ("btc-a -rpcwallet=miner gettransaction $T | jq .confirmations\nbtc-a getrawmempool", "T was un-confirmed, not cancelled.", "0 confirmations, back in the mempool"),
           "C9": ("mine 1", "T is confirmed again, in a different block.", "blockheight 104"),
           "C10": ("header work 1d00ffff 1d00ffff 1d00ffff\nheader work 1c7fffff 1c7fffff", "Worksheet: two harder blocks can outweigh three easier ones.", "2 blocks > 3 blocks in work")},
    submit="Tip records before/after, the state of T at each step, and the chainwork worksheet.",
    limits=["regtest blocks all have the same minimal target: unequal-work races are a worksheet here",
            "a reorganization never makes an invalid transaction valid"])

META["dlab05-wallet"] = dict(
    deck="DLAB 05 — Watch-Only Coordination and Recovery", stable="LAB-BTC-WALLET", session="5", minutes="180", lecture="M 3.1",
    network="regtest", network_why="Recovery tests need a wallet history we create and can reset; the signer is an offline regtest node.",
    goal="Separate watching from signing with descriptors and PSBTs, then compare a complete and an incomplete backup.",
    meaning=["Public descriptors let a coordinator see funds and build transactions without any private key.",
             "An offline signer approves a PSBT without network access or chain data.",
             "A backup is complete only if it restores both keys and the derivation paths that found the coins."],
    steps={"W1": ("btc-b getnetworkinfo | jq '{networkactive, connections}'\nbtc-b createwallet signer", "Node B never talks to the network.", "networkactive false, height 0"),
           "W2": ("btc-b -rpcwallet=signer listdescriptors | jq -r '.descriptors[].desc'", "Public descriptors: xpub + derivation path, receive /0/* and change /1/*.", "wpkh([fingerprint/84h/1h/0h]tpub…/0/*)"),
           "W3": (None, "The coordinator imports only public information.", "[true, true]"),
           "W4": (None, "Both compute the same address.", "SAME"),
           "W5": (None, "The coordinator sees the funds; the signer cannot (no chain).", "1.0 vs 0.0"),
           "W6": (None, "Build the PSBT where the chain is known.", "complete: false"),
           "W7": ("SIGNED=$(btc-b -rpcwallet=signer walletprocesspsbt $PSBT | jq -r .psbt)", "Sign where the keys are.", "final witness present, signer height still 0"),
           "W8": ("btc-a sendrawtransaction $(btc-a finalizepsbt $SIGNED | jq -r .hex)\nmine 1", "Broadcast from the online side.", "watch balance ≈ 0.6999"),
           "W9": (None, "Restore keys + both descriptors into a clean wallet.", "balance ≈ 0.6999"),
           "W10": (None, "Restore without the change descriptor.", "balance 0.00000000: the change is invisible")},
    submit="Role diagram (who holds what), a sanitized PSBT trace, and the complete-versus-incomplete recovery comparison.",
    limits=["the lab descriptors are regtest test keys",
            "real hardware signers add display verification and key protection that a regtest node does not"])

META["dlab06-attest"] = dict(
    deck="DLAB 06 — Device Evidence", stable="LAB-IOT-ATTEST", session="6", minutes="180",
    lecture="M 4.1 / M 4.2", network="none (simulation)",
    network_why="The collector's decision needs no blockchain: this is a local simulation of D17 and its verifier. Anchoring comes in DLAB 07/11.",
    goal="Run the D17 collector rule on fixed, signed reports and separate signature validity, authorization, freshness, context and truth.",
    meaning=["The verifier checks exact bytes under the operator's registered key, never a key carried by the report.",
             "Counter + enrollment version decide whether a valid report is a new event.",
             "A perfectly signed reading can still be false: no digital check establishes physical truth."],
    steps={"D0": ("cd /lab/d17\nd17 prepare-c0\nd17 registry", "Checkpoint C0: (D17, key-A, enrollment 3), last accepted 41.", "key-A 3 active, last 41"),
           "D1": ("d17 explain cases/R42.json", "The exact signed bytes and m = TaggedHash(schema, bytes).", "9 lines, seq=42"),
           "T01": ("d17 submit cases/R42.json\nd17 checkpoint save C1", "Accepted once; state C1.", "ACCEPTED — seq 41 -> 42"),
           "T02": (None, "Exact retry.", "NO_NEW_EVENT"),
           "T04": ("d17 checkpoint load C0\nd17 submit cases/R42-altered.json", "Bytes changed after signing.", "REJECT_SIGNATURE"),
           "T05": (None, "Validly signed for the wrong audience.", "REJECT_CONTEXT"),
           "T06": (None, "Delayed but unseen: ordering passes, age unknown.", "ACCEPTED (gap of 1)"),
           "T07": (None, "Late lower sequence.", "NO_NEW_EVENT"),
           "T08": (None, "A bad signature cannot poison the counter.", "REJECT_SIGNATURE, then R42 still ACCEPTED"),
           "T09": (None, "Reboot does not reset the collector.", "NO_NEW_EVENT"),
           "T10": (None, "A device cannot enrol itself.", "REJECT_AUTHORITY"),
           "T11": (None, "Possession of a key ≠ authorized binding.", "REJECT_AUTHORITY"),
           "T12": ("d17 authority offline\nd17 submit cases/R42.json\nd17 authority online", "Authority unknown → queue, do not accept.", "INDETERMINATE"),
           "T13": (None, "Unknown replay state is not zero.", "INDETERMINATE"),
           "T14": ("d17 checkpoint load C1\nd17 enroll --key key-B --enrollment 4 --pubkey $(jq -r .pubkey keys/key-B.json)\nd17 submit cases/RB1.json\nd17 submit cases/R43-after-cutover.json",
                   "Routine rotation decided by operator O.", "RB1 ACCEPTED; old key REJECT_AUTHORITY"),
           "T15": ("d17 checkpoint load C1\nd17 revoke --enrollment 3\nd17 submit cases/R43-after-cutover.json\n# then enrol key-B and submit RB1", "Compromise branch: revoke first.", "REJECT_AUTHORITY, then RB1 ACCEPTED"),
           "T17": ("d17 reports\nd17 show 1", "History keeps the original decision.", "#1 ACCEPTED is still recorded"),
           "T18": ("d17 submit cases/R42-false-reading.json\ncat ground-truth.csv", "A signed lie passes every digital check.", "ACCEPTED; clamp says 310 W")},
    submit="Verdict table T01–T18 (signature / authority / context / freshness / truth columns), the two lifecycle traces and the R42 evidence bundle.",
    limits=["simulation of a classroom protocol, not an IoT standard and not hardware attestation",
            "acceptance never proves the reading's age or physical truth"])

META["dlab07-anchor"] = dict(
    deck="DLAB 07 — Sensor Records and Merkle Anchoring", stable="LAB-INTEGRITY-ANCHOR", session="7", minutes="180", lecture="M 4.3",
    network="regtest (+ optional signet step)",
    network_why="Regtest gives a deterministic, instant anchor. An optional final step publishes one root on signet so a classmate can check it from another computer.",
    goal="Batch exact sensor records in a Merkle tree, anchor the root with OP_RETURN, and verify receipts against changed, missing and omitted evidence.",
    meaning=["One 32-byte root on chain commits to every record in the batch.",
             "A receipt (file + Merkle path + transaction) lets anyone check one record independently.",
             "Inclusion is not completeness: a valid receipt says nothing about records left out of the batch."],
    steps={"M1": ("cd /lab/records\nsha256sum r0*.csv", "Exact bytes, exact hashes.", "8 hashes"),
           "M2": ("merkle build r0*.csv", "RFC 9162 tree: leaf = SHA256(0x00‖bytes), node = SHA256(0x01‖L‖R).", "one root"),
           "M3": ("merkle anchor $ROOT", "A transaction with OP_RETURN 'BITCT' 01 root.", "txid in the mempool"),
           "M4": (None, "Mine and read the data output.", "OP_RETURN 4249544354 01 …"),
           "M5": ("merkle receipt --index 2 --txid $TXID -o /lab/r03.receipt.json r0*.csv", "A receipt for one record.", "leaf 2 of 8, 3 path hashes"),
           "M6": ("merkle verify /lab/r03.receipt.json r03.csv", "Four independent checks.", "VERIFIED"),
           "M7": (None, "One changed digit.", "FAIL at file bytes → NOT VERIFIED"),
           "M8": (None, "No path, no proof: the root cannot rebuild missing evidence.", "FAIL at Merkle path"),
           "M9": (None, "A batch that silently omits r05 still yields valid receipts.", "VERIFIED — compare with expected-set.txt")},
    submit="Hash list, root, txid, the three verdicts (changed / missing / omitted) and a claim-boundary note.",
    limits=["an anchor proves the bytes existed before the block, not when they were measured or that they are true",
            "regtest anchors are private to your laptop: only the signet step gives third-party evidence"])

META["dlab08-channel"] = dict(
    deck="DLAB 08 — Lightning Channel Lifecycle", stable="LAB-LN-CHANNEL", session="8", minutes="180", lecture="M 5.1",
    network="regtest", network_why="Opening, paying and closing need fast confirmations and a long force-close delay we can mine through in seconds.",
    goal="Open a channel, pay off-chain, close cooperatively, then force-close and follow the time-locked return to the chain.",
    meaning=["A channel is a 2-of-2 on-chain output; payments only update who could claim it.",
             "A cooperative close is an ordinary transaction both sides sign.",
             "A force close publishes the latest commitment: the closer waits a relative timelock, the peer does not."],
    steps={"L1": ("ln-alice getinfo\nln-bob getinfo", "Two LND nodes on one regtest node.", "0 channels"),
           "L2": ("ln-fund alice 1", "On-chain coins for Alice.", "100,000,000 sat"),
           "L3": ("BOB=$(ln-bob getinfo | jq -r .identity_pubkey)\nln-alice connect $BOB@bob:9735", "Peer connection (no money yet).", "bob listed as peer"),
           "L4": ("ln-alice openchannel --node_key $BOB --local_amt 500000", "The funding transaction enters the mempool.", "1 pending channel"),
           "L5": ("mine 3\nln-alice listchannels", "Confirmed: the channel is active.", "capacity 500000"),
           "L6": ("bitcoin-cli getrawtransaction $FUNDTX true | jq '.vout[] | {value, type: .scriptPubKey.type}'", "The 2-of-2 output on chain.", "witness_v0_scripthash"),
           "L7": ("INV=$(ln-bob addinvoice --amt 50000 | jq -r .payment_request)\nln-alice payinvoice --force $INV", "A payment with no on-chain transaction.", "SUCCEEDED; mempool empty"),
           "L8": (None, "Only the balances inside the channel moved.", "bob local 50000"),
           "L9": ("ln-alice closechannel --funding_txid … --output_index …\nmine 6", "Both sign one closing transaction.", "COOPERATIVE_CLOSE"),
           "L10": ("ln-alice openchannel --node_key $BOB --local_amt 400000\nmine 3\nINV2=$(ln-bob addinvoice --amt 20000 | jq -r .payment_request)\nln-alice payinvoice --force $INV2", "A second channel and a payment.", "SUCCEEDED"),
           "L11": ("ln-alice closechannel --force --funding_txid … --output_index …\nmine 6\nln-alice pendingchannels", "Alice publishes her commitment alone.", "4 outputs; blocks_til_maturity ≈ 139"),
           "L12": ("mine <blocks_til_maturity>\nln-alice closedchannels", "Bob was paid at once; Alice's coins return after the delay.", "LOCAL_FORCE_CLOSE")},
    submit="Channel ID, balance trace, funding/closing txids, and a comparison of the two close paths (who waits, why).",
    limits=["regtest with one implementation (LND v0.21.4): timings and channel types are implementation choices",
            "no watchtower or breach (old state) case is executed here"])

META["dlab09-routing"] = dict(
    deck="DLAB 09 — Routing with Hidden Liquidity", stable="LAB-LN-ROUTING", session="9", minutes="180", lecture="M 5.2",
    network="regtest", network_why="We need a frozen four-node topology whose private balances we know as evaluators; public networks never reveal them.",
    goal="Predict a route from public gossip, watch it fail on hidden liquidity, inspect the retry, then change one condition.",
    meaning=["Gossip shows capacities and fees, never balances.",
             "A sender learns liquidity only by trying: failures become local evidence (mission control).",
             "The cheapest advertised route is not always a route that can carry the payment."],
    steps={"R0": ("ln-topology", "Four nodes, four channels, fixed fees (about 2 minutes).", "topology ready"),
           "R1": ("lnview graph", "Alice's public view.", "bob cheap (10 ppm), carol expensive (2000 ppm)"),
           "R2": ("DAVE=$(ln-dave getinfo | jq -r .identity_pubkey)\nln-alice queryroutes --dest $DAVE --amt 300000", "Predicted route.", "via bob, 4 sat fee"),
           "R3": ("INV=$(ln-dave addinvoice --amt 300000 | jq -r .payment_request)\nln-alice payinvoice --force --json $INV > /lab/pay1.json\nlnview payment /lab/pay1.json",
                  "Attempt, failure, retry.", "bob route FAILED (TEMPORARY_CHANNEL_FAILURE), carol route SUCCEEDED"),
           "R4": ("lnview balances", "Evaluator only: the hidden balances.", "bob could send only ~96,000 to dave"),
           "R5": ("ln-alice querymc", "What Alice remembers.", "bob→dave failed at 300000"),
           "R6": ("BINV=$(ln-bob addinvoice --amt 400000 | jq -r .payment_request)\nln-dave payinvoice --force $BINV\nln-alice resetmc", "Change one condition: refill bob→dave.", "SUCCEEDED"),
           "R7": (None, "Same payment again.", "one attempt via bob, fee 4 sat")},
    submit="Topology snapshot, your prediction, the attempt trace, and a short interpretation separating public graph, local feedback and hidden state.",
    limits=["retry and route choice are LND-specific (mission control); other implementations differ",
            "four nodes illustrate the mechanism; they are not a dataset (see DLAB 10)"])

META["dlab10-graph"] = dict(
    deck="DLAB 10 — Graph Learning with Hidden Liquidity", stable="LAB-LN-GRAPH", session="10", minutes="180", lecture="M 5.2",
    network="none (simulation)", network_why="No live probing: a deterministic simulator provides observations, hidden balances and labels in separate tables.",
    goal="Test whether a small message-passing model beats simpler baselines at predicting directed liquidity, and diagnose leakage.",
    meaning=["Only observable columns may enter a model; hidden balances are for evaluation.",
             "Train on earlier periods, test on later ones; choose settings on validation only.",
             "A small or negative gain is a valid scientific result; leakage makes a fake large one."],
    steps={}, submit="Dataset/seed, permitted features, split boundaries, metric table, one failure case, leakage explanation, conclusion with limits.",
    limits=["one synthetic simulator and topology: no claim about the live Lightning Network",
            "no routing improvement is shown: that needs a separate controlled routing experiment"])

META["dlab11-esp32"] = dict(
    deck="DLAB 11 — ESP32 Sensor Readings Anchored on Bitcoin", stable="LAB-IOT-ESP32-ANCHOR (new)", session="extension of 6–7", minutes="180",
    lecture="M 4.1 → M 4.3", network="regtest (+ optional signet publication)",
    network_why="Regtest anchors every minute with blocks every 30 s, so the whole pipeline is visible in class. A regtest anchor convinces only you: the optional signet step lets an outside auditor check one root later.",
    goal="Make D17 concrete: a Wokwi ESP32 signs each reading; the Docker gateway verifies, batches into a Merkle tree, anchors the root and issues receipts that an auditor can check later.",
    meaning=["The device signs exact bytes (BIP340); the network and broker are untrusted transport.",
             "The gateway applies the D17 rule, then commits accepted readings to Bitcoin in periodic Merkle batches.",
             "A later audit detects altered records; it cannot detect a false reading or a reading never batched."],
    steps={"E0": ("# 1. edit .env: GROUP=<your group code>\ndocker compose up -d --wait\ndocker compose exec lab bash\nd17 registry", "The gateway listens; nobody is enrolled.", "empty registry"),
           "E1": ("d17 keygen", "Factory provisioning: create the meter's key.", "secret (paste into Wokwi) and public key"),
           "E2": ("Wokwi: set GROUP and DEVICE_SECRET_HEX in sketch.ino, press ▶", "The meter signs and publishes every 15 s.", "Serial monitor: report bytes, signature, published OK"),
           "E3": ("d17 reports", "Signed, but not authorized.", "REJECT_AUTHORITY"),
           "E4": ("d17 enroll --enrollment 1 --pubkey <public key shown by the ESP32>", "Operator O binds the key to D17.", "operator O authorized (D17, key-A, enrollment 1)"),
           "E5": ("d17 reports", "Readings are now accepted.", "ACCEPTED"),
           "E6": ("d17 batches", "Every minute: Merkle batch → OP_RETURN → block.", "anchored → confirmed"),
           "E7": ("d17 receipt <id> -o /lab/receipt.json\nd17 audit /lab/receipt.json", "An independent four-step audit.", "VERIFIED, with its claim limits"),
           "E8": ("d17 tamper <id> --value 400\nd17 receipt <id> -o /lab/after.json\nd17 audit /lab/after.json\nd17 audit /lab/receipt.json", "A dishonest collector rewrites history.", "after: NOT VERIFIED; kept receipt: VERIFIED"),
           "E9": ("Wokwi: press REPLAY, then TAMPER   (no Wokwi: d17-sim --resend-last replay|tamper)\nd17 reports --last 4", "Attacks on the wire.", "NO_NEW_EVENT, REJECT_SIGNATURE"),
           "E10": ("d17 gaps", "Missing sequence numbers are evidence to investigate.", "gaps listed"),
           "E11": ("open http://localhost:8080/iot", "The whole pipeline on one page.", "registry, reports, batches")},
    submit="Your enrolled public key, a verified receipt, the tamper/replay verdicts, the gap list, and a claim-boundary paragraph (what the anchor proves and does not prove).",
    limits=["Wokwi is a simulator: the 'current sensor' is a slider",
            "the counter starts from the boot time because Wokwi forgets flash: a real meter keeps it in secure storage",
            "a regtest anchor is private evidence; public evidence needs signet (or mainnet)"])
